version: '3'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: miraestate-backend
    container_name: miraestate-backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - "DB_CONNECTION=mysql"
      - "DB_HOST=mysql"
      - "DB_PORT=3306"
      - "DB_DATABASE=miraestate"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=7578808757#Ramz"
    depends_on:
      - mysql
    ports:
      - "9000:9000"  # Add this line to map port 9000 on the host to port 9000 in the container

  # MySQL Database
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: miraestate
      MYSQL_ROOT_PASSWORD: "Ramz#7578808757"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "7578808757#Ramz"
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
